version: '3.4'

services:
  seq:
    image: datalust/seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_PASSWORD=admin

    volumes:
      - seq-data:/data
volumes:
  seq-data:
